Description of dhmm_em_demo
dhmm_em_demo
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
dhmm_em LEARN_DHMM Find the ML/MAP parameters of an HMM with discrete outputs using EM.
dhmm_logprob LOG_LIK_DHMM Compute the log-likelihood of a dataset using a discrete HMM
dhmm_sample SAMPLE_DHMM Generate random sequences from a Hidden Markov Model with discrete outputs.
This function is called by:
testHMM Run all the demos, to check everything is "syntactically correct"
SOURCE CODE
O = 3;
Q = 2;
% "true" parameters
prior0 = normalize(rand(Q,1));
transmat0 = mk_stochastic(rand(Q,Q));
obsmat0 = mk_stochastic(rand(Q,O));
% training data
T = 5;
nex = 10;
data = dhmm_sample(prior0, transmat0, obsmat0, T, nex);
% initial guess of parameters
prior1 = normalize(rand(Q,1));
transmat1 = mk_stochastic(rand(Q,Q));
obsmat1 = mk_stochastic(rand(Q,O));
% improve guess of parameters using EM
[LL, prior2, transmat2, obsmat2] = dhmm_em(data, prior1, transmat1, obsmat1, 'max_iter', 30);
LL
% use model to compute log likelihood
loglik = dhmm_logprob(data, prior2, transmat2, obsmat2)
% log lik is slightly different than LL(end), since it is computed after the final M step